/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ob_android_Stream */

#ifndef _Included_ob_android_Stream
#define _Included_ob_android_Stream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ob_android_Stream
 * Method:    stream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ob_android_Stream_stream
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
